/**
 * Minimal RFC 5545 (.ics / VCALENDAR) generator for the Adaptive Study
 * Partner planner.
 *
 * Why hand-rolled instead of `ics` / `ical-generator`:
 *   - We emit ~15 lines per event. The libraries are 30+ KB minified
 *     and add nothing we need.
 *   - Determinism matters for the demo. A custom generator is reviewable
 *     in one screen; opening Calendar.app and seeing a study slot land
 *     at the right time should not depend on a transitive dep update.
 *
 * Scope choices:
 *   - One-shot, non-recurring events only (no RRULE). The plan is for
 *     a specific week; we re-export every week.
 *   - UTC `DTSTART`/`DTEND` so timezone interpretation is unambiguous
 *     across Apple Calendar, Google Calendar (web), and Outlook.
 *   - Stable UID per (weekStart, slot, day-index) so re-importing the
 *     same week updates rather than duplicates the events.
 */
import type { PlanSlot, WeekPlan } from "@/lib/planner/types";
import {
  DAY_END_MIN,
  DAY_START_MIN,
  SLOT_VISUAL_MIN,
  layoutDay,
} from "@/lib/planner/day-schedule";
import { eventsForDay, type LifeEvent } from "@/lib/planner/life-events";
import {
  rulesAsLifeEvents,
  type AvailabilityRule,
} from "@/lib/calendar/availability-rules";

const PRODID = "-//Nexford//Adaptive Study Partner//EN";

interface IcsEvent {
  uid: string;
  summary: string;
  description: string;
  startUtc: Date;
  endUtc: Date;
}

/** Pad and format a Date as RFC-5545 UTC stamp: YYYYMMDDTHHMMSSZ. */
function fmtUtc(d: Date): string {
  const pad = (n: number, w = 2) => String(n).padStart(w, "0");
  return (
    `${d.getUTCFullYear()}` +
    `${pad(d.getUTCMonth() + 1)}` +
    `${pad(d.getUTCDate())}` +
    `T${pad(d.getUTCHours())}` +
    `${pad(d.getUTCMinutes())}` +
    `${pad(d.getUTCSeconds())}Z`
  );
}

/** RFC 5545 line-fold safe escaping for SUMMARY/DESCRIPTION fields. */
function escapeIcsText(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\r?\n/g, "\\n");
}

function buildVEvent(e: IcsEvent): string {
  return [
    "BEGIN:VEVENT",
    `UID:${e.uid}`,
    `DTSTAMP:${fmtUtc(new Date())}`,
    `DTSTART:${fmtUtc(e.startUtc)}`,
    `DTEND:${fmtUtc(e.endUtc)}`,
    `SUMMARY:${escapeIcsText(e.summary)}`,
    `DESCRIPTION:${escapeIcsText(e.description)}`,
    "END:VEVENT",
  ].join("\r\n");
}

function wrapVCalendar(events: string[]): string {
  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    `PRODID:${PRODID}`,
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    ...events,
    "END:VCALENDAR",
    "",
  ].join("\r\n");
}

/**
 * Compute the actual wall-clock window each PlanSlot occupies on its
 * day, by running the same `layoutDay` placement the calendar render
 * uses. This guarantees the .ics agrees with what's on screen — no
 * "the calendar said 11:30 but Google Calendar says 09:00" surprises.
 */
function placeSlotsForExport(
  plan: WeekPlan,
): Array<{ slot: PlanSlot; date: string; startMin: number; endMin: number }> {
  const out: Array<{
    slot: PlanSlot;
    date: string;
    startMin: number;
    endMin: number;
  }> = [];
  const rules: AvailabilityRule[] = plan.availabilityRules ?? [];
  for (const day of plan.days) {
    const seedEvents = eventsForDay(day.dayLabel);
    const ruleEvents = rulesAsLifeEvents(
      rules,
      day.dayLabel as Parameters<typeof rulesAsLifeEvents>[1],
    );
    const lifeEvents: LifeEvent[] = [...seedEvents, ...ruleEvents];
    const { studyBlocks } = layoutDay(day.slots, lifeEvents);
    for (const block of studyBlocks) {
      out.push({
        slot: block.slot,
        date: day.date,
        startMin: block.startMin,
        endMin: Math.min(
          block.startMin + SLOT_VISUAL_MIN,
          DAY_END_MIN,
        ),
      });
    }
  }
  // Belt-and-braces: clamp degenerate cases so we never emit 0-length
  // events (some calendars silently drop them).
  return out.filter((r) => r.endMin > r.startMin && r.startMin >= DAY_START_MIN);
}

function isoDateAtMin(isoDate: string, minutesSinceMidnight: number): Date {
  // Treat the date as local civil time so the calendar event lands when
  // the student actually expects to study, not "08:00 UTC".
  const [y, m, d] = isoDate.split("-").map((n) => parseInt(n, 10));
  const local = new Date(
    y,
    (m ?? 1) - 1,
    d ?? 1,
    Math.floor(minutesSinceMidnight / 60),
    minutesSinceMidnight % 60,
    0,
    0,
  );
  return local;
}

function uidFor(weekStart: string, date: string, concept: string): string {
  return `${date}-${concept}-${weekStart}@nexford.adaptive`;
}

function describeSlot(slot: PlanSlot): string {
  return [
    `Concept: ${slot.conceptLabel}`,
    `Kind: ${slot.kind}`,
    `Cognitive load: ${slot.load}/3`,
    "",
    slot.rationale,
    "",
    "Generated by the Nexford Adaptive Study Partner planner.",
  ].join("\n");
}

/**
 * Emit a one-event .ics for a single accepted study slot on a specific
 * date. Used by the per-block "Add to calendar" icon button.
 */
export function slotToIcs(
  slot: PlanSlot,
  date: string,
  startMin: number,
  endMin: number,
  weekStart: string,
): string {
  const event = buildVEvent({
    uid: uidFor(weekStart, date, slot.concept),
    summary: `${slot.conceptLabel} — ${slot.kind}`,
    description: describeSlot(slot),
    startUtc: isoDateAtMin(date, startMin),
    endUtc: isoDateAtMin(date, endMin),
  });
  return wrapVCalendar([event]);
}

/**
 * Emit a full-week .ics covering every accepted slot in the plan. Used
 * by the "Download week" button next to "Accept Plan".
 */
export function weekToIcs(plan: WeekPlan): string {
  const placed = placeSlotsForExport(plan);
  const events = placed.map((p) =>
    buildVEvent({
      uid: uidFor(plan.weekStart, p.date, p.slot.concept),
      summary: `${p.slot.conceptLabel} — ${p.slot.kind}`,
      description: describeSlot(p.slot),
      startUtc: isoDateAtMin(p.date, p.startMin),
      endUtc: isoDateAtMin(p.date, p.endMin),
    }),
  );
  return wrapVCalendar(events);
}

/**
 * Trigger a browser download of the given .ics body. Called from the
 * /plan page button handlers. SSR-safe by being a no-op outside the
 * browser; in practice it's only called from `onClick` so this is just
 * defence in depth.
 */
export function downloadIcs(filename: string, body: string): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([body], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function suggestSlotFilename(
  slot: PlanSlot,
  date: string,
): string {
  const safeConcept = slot.concept.replace(/[^a-z0-9_-]+/gi, "_");
  return `nexford-${date}-${safeConcept}.ics`;
}

export function suggestWeekFilename(weekStart: string): string {
  return `nexford-week-${weekStart}.ics`;
}
